logging:
    level:
        liquibase: INFO
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Admin$123
        url: jdbc:mysql://localhost:3306/liquibase_demo
        username: root
    liquibase:
        change-log: classpath:/db/changelog/changelog-master.xml
